### PR TITLE
Fixed most of pthreadlib warnings

### PR DESCRIPTION
**Pull request by infraredsqy**
Fixed most of the warnings appeared in pthreadlib osal.
Here is the only warning that remains:

```
src/nautilus/libccompat.c:1038:11: warning: address of stack memory associated with local variable '__environ' returned [-Wreturn-stack-address]
  return &__environ;
          ^~~~~~~~~
```

### CODE REVIEW

**Comment by MJChku** [comment]
The finalized branch is switched to "openmp" and this branch is not used anymore.
For setenv/getenv, it's totally based on Prof.Dinda's approach;
For .config, probably not add to commit
Please make changes on based on openmp branch,
and environ is changed on openmp branch as well, Openmp library changes accordingly, there is an openmp.tar in `jiacheng`  branch, please use that one (changed one line).

Also, in openmp branch, code is moved to src/rt/kmp/ .. unnecessary codes are removed

**Comment by infraredsqy** [comment]
> The finalized branch is switched to "openmp" and this branch is not used anymore.
> For setenv/getenv, it's totally based on Prof.Dinda's approach;
> For .config, probably not add to commit
> Please make changes on based on openmp branch,
> and environ is changed on openmp branch as well, Openmp library changes accordingly, there is an openmp.tar in `jiacheng` branch, please use that one (changed one line).
> 
> Also, in openmp branch, code is moved to src/rt/kmp/ .. unnecessary codes are removed

the branch openmp has not been updated to the latest openmp version. You can see that there are large amount of conflicts involved. This is supposed to be a small warning fix.
Not changing getenv/setenv for now.
Will add gitignore settings for .config.

**Comment by MJChku** [comment]
If you pulled branch `openmp` last time,  you have to pull it again from github, it's been deleted and created and then updated.

**Comment by MJChku** [comment]
also add `-w` flag can skip all the warnings

**Pull request merged**
